namespace PIFilmAutoDetachCleanMC.Process
{
    public enum EProcess
    {
        Root,
        InConveyor,
        InWorkConveyor,
        BufferConveyor,
        OutWorkConveyor,
        OutConveyor,
        RobotLoad,
        VinylClean,
        FixtureAlign,
        TransferFixture,
        Detach,
        RemoveFilm,
        GlassTransfer,
        GlassAlignLeft,
        GlassAlignRight,
        TransferInShuttleLeft,
        TransferInShuttleRight,
        WETCleanLeft,
        WETCleanRight,
        TransferRotationLeft,
        TransferRotationRight,
        AFCleanLeft,
        AFCleanRight,
        UnloadTransferLeft,
        UnloadTransferRight,
        UnloadAlign,
        RobotUnload,
    }
}
